#!/usr/bin/env python3
"""Build the CiV TCPA prospect list CSV.

Scoring model (0-100), see 02-risk-model.md:
  s_lit   0-30  Litigation & enforcement history (strongest observable signal)
  s_lead  0-25  Lead-sourcing / consent-provenance posture (root cause of most exposure)
  s_vol   0-20  Outbound volume & dialer posture
  s_vert  0-12  Vertical base rate (WebRecon case-mix)
  s_geo   0-08  Regulatory surface (mini-TCPA states, multistate footprint)
  s_gap   0-05  Compliance maturity gap
"""
import csv, sys

H = [
 "Rank","Company","Vertical","Sub-vertical","Business Model","HQ (City, State)",
 "Other US Call Center Sites","Call Center Seats (est.)","Seats Basis / Confidence",
 "Total Employees","Annual Revenue","Revenue Basis / Confidence",
 "# of Clients","Client List / Key Clients",
 "Outbound Calling Evidence","TCPA Exposure Evidence (Trigger)","Lead-Sourcing Posture",
 "Litigation /30","Lead Source /25","Volume /20","Vertical /12","Geo /8","Gap /5",
 "TCPA RISK SCORE","Risk Band","Solvency / Reputability","CiV Fit",
 "Buying Trigger & Timing","Entry Point (Title)","Opening Hook","Sources","Overall Confidence",
]

def band(s):
    if s >= 80: return "1 - CRITICAL"
    if s >= 65: return "2 - HIGH"
    if s >= 50: return "3 - ELEVATED"
    if s >= 35: return "4 - MODERATE"
    return "5 - WATCH"

R = []
def add(**k):
    k["score"] = k["lit"]+k["lead"]+k["vol"]+k["vert"]+k["geo"]+k["gap"]
    R.append(k)

# ---------------------------------------------------------------- INSURANCE
add(co="Liberty Mutual Insurance", v="Insurance", sv="P&C carrier (personal lines)",
    bm="B2C direct + agency", hq="Boston, MA", sites="Multiple US service/sales centers",
    seats="2,000+ (est.)", sb="Est. from sales/service headcount; not disclosed - LOW",
    emp="~45,000", rev="~$50B", rb="Public financial reports - HIGH",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Operates outbound telemarketing campaigns using purchased third-party aggregator leads (per class cert order)",
    te="Ward v. Liberty Mutual - TWO TCPA classes certified 6/12/2026; ~$30M exposure; leads purchased from All Web Leads",
    lp="Buys aggregated third-party leads - the certified failure mode",
    lit=30, lead=25, vol=17, vert=12, geo=8, gap=2,
    solv="Strong - Fortune 100 carrier", fit="C - enterprise cycle, in-house legal, but reference logo",
    trig="Class certified 6/2026 - remediation budget unlocked NOW; carrier-wide lead audit likely underway",
    ep="Chief Compliance Officer / AGC Regulatory / VP Distribution Compliance",
    hook="Ward certification turned your vendor lead files into class evidence. We reconstruct consent provenance per lead so the next cert motion fails.",
    src="natlawreview.com; tcpaworld.com 6/15/2026; agencychecklists.com 6/20/2026", conf="HIGH on trigger; LOW on seats")

add(co="All Web Leads, Inc.", v="Insurance", sv="Lead generator / aggregator",
    bm="B2B lead seller", hq="Austin, TX", sites="Austin, TX",
    seats="150-400 (est.)", sb="Est. from lead-gen ops scale - LOW",
    emp="Not public", rev="Not public", rb="Private - NONE",
    nclients="Dozens (carriers + agencies)", clients="Liberty Mutual (named in Ward); carrier/agency buyers - full list not public",
    oe="Generates and sells insurance leads into outbound calling programs",
    te="Named as lead source in Ward v. Liberty Mutual class cert; separately sued in TX federal court alleging systematically falsified leads",
    lp="Originates and resells leads - consent provenance is the product",
    lit=28, lead=25, vol=12, vert=12, geo=8, gap=4,
    solv="Operating - allegations unproven; diligence before outreach", fit="A - acute, mid-market, existential",
    trig="Named in a certified class + a fraud-flavored suit; buyers are demanding proof of consent right now",
    ep="CEO / General Counsel / Head of Compliance",
    hook="Your buyers just watched Liberty Mutual get certified on your leads. Certifiable consent provenance is now your commercial moat, not overhead.",
    src="natlawreview.com; tcpaworld.com 6/15/2026", conf="HIGH on trigger; NONE on financials")

add(co="Farmers Insurance Exchange", v="Insurance", sv="P&C carrier + captive agency",
    bm="B2C via agency force", hq="Woodland Hills, CA", sites="Multiple regional centers",
    seats="1,500+ (est.)", sb="Est.; agency force calls separately - LOW",
    emp="~21,000", rev="~$20B+", rb="Reported - MEDIUM",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Agency-force telemarketing; settlements cover calls placed by appointed agencies on Farmers' behalf",
    te="$2,875,000 TCPA settlement preliminarily approved 4/28/2026 (agency calls, DNC classes); separate $1.25M Heckathorn TCPA settlement",
    lp="Distributed agency calling - agent-level lead buying is the blind spot",
    lit=27, lead=18, vol=16, vert=12, geo=8, gap=3,
    solv="Strong - major national carrier", fit="B - agency-channel governance is a real gap",
    trig="Two settlements inside 24 months; vicarious liability for appointed agents is unresolved",
    ep="Chief Compliance Officer / VP Agency Operations",
    hook="Both settlements came from agent-placed calls you did not dial. Agent-channel consent governance is the unfixed root cause.",
    src="classaction.org; programbusiness.com; claimdepot.com/heckathorn", conf="HIGH on trigger")

add(co="American Income Life (Globe Life)", v="Insurance", sv="Life / final expense",
    bm="B2C direct + agent force", hq="Waco, TX", sites="Multiple US agency offices",
    seats="1,000+ (est.)", sb="Est. from agent force - LOW",
    emp="~3,000 corporate + large agent force", rev="Globe Life ~$5.8B", rb="Public filings - HIGH",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Agent-driven outbound calling on purchased and referral leads",
    te="$14M TCPA class action settlement over allegedly unsolicited sales calls",
    lp="Agent-purchased leads with weak central control",
    lit=25, lead=20, vol=16, vert=12, geo=8, gap=3,
    solv="Strong - NYSE parent", fit="B - large but real recurring pain",
    trig="Eight-figure settlement; agent-channel controls under board scrutiny",
    ep="Chief Compliance Officer / VP Agency Compliance",
    hook="A $14M settlement bought you a remediation mandate, not a fix. The agent lead pipeline is still un-instrumented.",
    src="TCPA settlement reporting; leadshook TCPA settlement roundup", conf="MEDIUM")

add(co="EverQuote, Inc.", v="Insurance", sv="Lead marketplace / comparison",
    bm="B2B lead + call seller", hq="Cambridge, MA", sites="Belfast, ME; Evansville, IN (est.)",
    seats="300-600 (est.)", sb="Est. from in-house agency + call ops - LOW",
    emp="~600-800", rev="$500.2M (2024)", rb="Public filings - HIGH",
    nclients="Hundreds of carriers & agents", clients="Major P&C carriers and independent agents; buyer roster partially public via partner disclosures",
    oe="Confirmed Convoso outbound dialer customer; operates in-house call scheduler and outbound agency",
    te="Structural: sells leads/calls into buyer outbound programs; marketplace model is the primary vicarious-liability vector post-IMC",
    lp="Originates + distributes leads to many buyers simultaneously",
    lit=12, lead=25, vol=17, vert=12, geo=8, gap=3,
    solv="Strong - NASDAQ listed, profitable", fit="A - sells compliance as differentiation",
    trig="Post-IMC, buyers demand named-party consent; marketplaces that can certify provenance win share",
    ep="General Counsel / VP Compliance / Chief Revenue Officer",
    hook="Your buyers now inherit your consent language. Certifiable per-buyer provenance is a pricing advantage, not a cost center.",
    src="convoso.com customer story; company financials; wikipedia", conf="HIGH on revenue/dialer")

add(co="MediaAlpha, Inc.", v="Insurance", sv="Programmatic lead/call exchange",
    bm="B2B exchange", hq="Los Angeles, CA", sites="Remote-first",
    seats="N/A - exchange, minimal own dialing", sb="Model is programmatic, not seat-based - HIGH",
    emp="~300", rev="$864.7M (2024)", rb="Public filings - HIGH",
    nclients="Tier-1 carriers + agencies", clients="Major P&C carriers; transaction value >$1.5B",
    oe="Routes calls and leads into buyer outbound programs via real-time bidding",
    te="Structural: RTB routing makes consent-string integrity the single point of failure across every downstream buyer",
    lp="Real-time exchange - consent travels with the bid or it does not travel",
    lit=10, lead=25, vol=14, vert=12, geo=8, gap=3,
    solv="Strong - NYSE listed", fit="A - infrastructure-level compliance buyer",
    trig="Exchange economics reward provable consent; one bad source contaminates every buyer",
    ep="General Counsel / VP Trust & Compliance",
    hook="In an RTB exchange, consent provenance either travels with the bid or every buyer inherits your worst publisher.",
    src="company financials; growthsharematrix; abovo market analysis", conf="HIGH on revenue")

add(co="SelectQuote, Inc.", v="Insurance", sv="Medicare / life telesales",
    bm="B2C telesales", hq="Overland Park, KS", sites="San Diego CA; Des Moines IA; Indianapolis IN (est.)",
    seats="2,000-3,000 (est. peak AEP)", sb="Est. from licensed agent force; seasonal surge - MEDIUM",
    emp="~3,000-5,000 (seasonal)", rev="~$1.5B", rb="Public filings - HIGH",
    nclients="Carrier partners", clients="Major Medicare Advantage carriers (Humana, UnitedHealthcare, Aetna et al.)",
    oe="Phone-led distribution is the entire business model; high-volume licensed-agent outbound",
    te="DOJ False Claims Act complaint-in-intervention filed 5/1/2025 naming SelectQuote (kickback allegations); heavy regulated-marketing scrutiny + CMS marketing rules",
    lp="Buys Medicare leads at scale during AEP surge",
    lit=18, lead=22, vol=20, vert=12, geo=8, gap=3,
    solv="Strong - NYSE listed", fit="A - seasonal surge = seasonal risk spike",
    trig="DOJ action + AEP (Oct 15-Dec 7) surge staffing; compliance budget approved pre-AEP",
    ep="Chief Compliance Officer / SVP Sales Operations",
    hook="AEP triples your dialing and your vendor lead mix in eight weeks. That surge is when consent provenance breaks.",
    src="justice.gov press release; medicaremarketinsights; company financials", conf="HIGH on DOJ action")

add(co="GoHealth, Inc.", v="Insurance", sv="Medicare telesales",
    bm="B2C telesales + lead referral", hq="Chicago, IL", sites="Charlotte NC; Lindon UT (est.)",
    seats="1,500-2,500 (est. peak AEP)", sb="Est.; seasonal - MEDIUM",
    emp="~2,500 (seasonal)", rev="~$700M-800M", rb="Public filings - MEDIUM",
    nclients="Carrier partners", clients="Major Medicare Advantage carriers; 'Encompass' warm-lead referral partners",
    oe="Generates warm leads and transfers to carrier partners - outbound + transfer model",
    te="Named in DOJ FCA complaint-in-intervention 5/1/2025; company also underwent Chapter 11 restructuring",
    lp="Both buys leads and generates/transfers them - dual exposure",
    lit=18, lead=23, vol=18, vert=12, geo=8, gap=4,
    solv="CAUTION - restructuring history; verify current financial footing", fit="B - verify solvency first",
    trig="DOJ action + restructuring = new leadership, new compliance mandate",
    ep="Chief Compliance Officer / General Counsel",
    hook="Encompass transfers put you on both sides of the consent chain. Both sides are discoverable.",
    src="justice.gov; bondoro.com GoHealth Ch11 summary; stocktitan", conf="MEDIUM - verify solvency")

add(co="eHealth, Inc.", v="Insurance", sv="Medicare / IFP telesales",
    bm="B2C telesales", hq="Santa Clara, CA", sites="Gold River CA; Indianapolis IN; Xiamen (offshore)",
    seats="1,200-2,000 (est. peak AEP)", sb="Est.; seasonal - MEDIUM",
    emp="~2,000+ (seasonal)", rev="~$500M", rb="Public filings - HIGH",
    nclients="Carrier partners", clients="Major Medicare Advantage and IFP carriers",
    oe="Confirmed outbound lead calling as core acquisition motion",
    te="Named in DOJ FCA complaint-in-intervention 5/1/2025",
    lp="Purchases Medicare leads; heavy AEP vendor reliance",
    lit=17, lead=22, vol=18, vert=12, geo=8, gap=3,
    solv="Adequate - NASDAQ listed; margin pressure", fit="A - mid-cap, real pain, reachable",
    trig="DOJ action; AEP surge; CMS marketing rule tightening",
    ep="Chief Compliance Officer / VP Sales Ops",
    hook="CMS marketing rules and TCPA now police the same call. One recording, two regulators, zero margin for provenance gaps.",
    src="justice.gov; medicaremarketinsights; company financials", conf="MEDIUM-HIGH")

add(co="Spring Venture Group", v="Insurance", sv="Medicare Supp / Advantage telesales",
    bm="B2C telesales", hq="Kansas City, MO", sites="Kansas City, MO (primary)",
    seats="800-1,500 (est.)", sb="Est. from licensed agent model - LOW",
    emp="~1,000-1,500", rev="Not public (PE-backed, Corsair Capital)", rb="Private - NONE",
    nclients="Carrier partners", clients="Medicare Supplement/Advantage carriers via United Medicare Advisors & SmartMatch",
    oe="Direct-to-consumer telesales is the stated business model across two agency brands",
    te="Structural: high-volume senior-targeted outbound; ALMIA member (industry self-regulation signals known exposure)",
    lp="Buys Medicare leads at volume",
    lit=8, lead=22, vol=18, vert=12, geo=8, gap=4,
    solv="Strong - Corsair Capital backed", fit="A - PE-backed, mid-market, compliance is a diligence item",
    trig="PE ownership = exit prep; TCPA contingent liability is a valuation haircut at diligence",
    ep="General Counsel / Chief Compliance Officer / CFO",
    hook="At exit, unprovable consent becomes an escrow holdback. Provenance is enterprise value, not overhead.",
    src="corsair-capital.com; springventuregroup.com; ALMIA membership", conf="MEDIUM")

add(co="TRANZACT (Willis Towers Watson)", v="Insurance", sv="Medicare direct-response",
    bm="B2B2C outsourced acquisition", hq="Fort Lee, NJ", sites="Fort Lee NJ; Bala Cynwyd PA (est.)",
    seats="1,000-2,000 (est.)", sb="Est. from direct-response model - LOW",
    emp="~1,500+", rev="Not separately disclosed (WTW segment)", rb="Parent public; segment not broken out - LOW",
    nclients="Major MA carriers", clients="Medicare Advantage carriers - operates acquisition on their behalf",
    oe="Direct-response TV/digital into inbound + outbound telesales for carrier clients",
    te="Structural: performs calling ON BEHALF of carriers - classic vicarious liability posture; ALMIA member",
    lp="Runs the lead-to-call chain for carrier clients - owns the consent record",
    lit=8, lead=23, vol=18, vert=12, geo=8, gap=3,
    solv="Strong - WTW subsidiary", fit="B - enterprise parent, but the operating unit feels the pain",
    trig="Carrier clients now demand indemnity + provenance evidence in renewals",
    ep="Head of Compliance / General Counsel / Client Services Lead",
    hook="Your carrier clients are pushing TCPA indemnity down to you. Provenance evidence is now a contract renewal term.",
    src="ALMIA membership; WTW disclosures", conf="LOW-MEDIUM")

add(co="HealthPlanOne / ClearMatch", v="Insurance", sv="Medicare telesales",
    bm="B2C telesales", hq="Trumbull, CT", sites="CA, FL, NY licensed ops",
    seats="500-1,200 (est.)", sb="Est. - LOW", emp="~800-1,500", rev="Not public", rb="Private - NONE",
    nclients="Carrier partners", clients="Medicare Advantage/Supplement carriers",
    oe="Licensed telesales agency model across multiple states",
    te="Structural: senior-targeted outbound at scale; ALMIA member; operates in FL (FTSA private right of action)",
    lp="Buys Medicare leads",
    lit=7, lead=22, vol=16, vert=12, geo=8, gap=4,
    solv="Operating - private", fit="A - mid-market, no in-house TCPA bench",
    trig="FL operations expose it to FTSA statutory damages independent of federal law",
    ep="General Counsel / VP Compliance",
    hook="Your Florida book is exposed under FTSA whether or not the FCC rule survived. State law never blinked.",
    src="ALMIA membership; company disclosures", conf="LOW-MEDIUM")

add(co="e-TeleQuote Insurance", v="Insurance", sv="Medicare telesales",
    bm="B2C telesales", hq="Clearwater, FL", sites="Clearwater, FL",
    seats="600-1,200 (est.)", sb="Est. - LOW", emp="~1,000", rev="Not public", rb="Private - NONE",
    nclients="Carrier partners", clients="Medicare Advantage carriers",
    oe="Pure telesales Medicare distributor",
    te="HQ in Florida - FTSA exposure (3-call/24hr cap, 8pm cutoff, $500-$1,500 private right of action) on top of federal TCPA",
    lp="Buys Medicare leads at volume",
    lit=8, lead=22, vol=17, vert=12, geo=8, gap=4,
    solv="Operating - verify current status", fit="A - FL-domiciled telesales is the highest-density risk profile",
    trig="Florida domicile + senior targeting = FTSA plaintiff bar's preferred defendant",
    ep="General Counsel / Chief Compliance Officer",
    hook="A Clearwater telesales floor calling seniors is the FTSA bar's ideal defendant. Federal relief did nothing for you.",
    src="ALMIA membership; insurance-forums industry discussion", conf="LOW-MEDIUM")

add(co="SmartFinancial", v="Insurance", sv="Lead marketplace",
    bm="B2B lead seller", hq="Columbus, OH", sites="Columbus OH; Newport Beach CA",
    seats="100-300 (est.)", sb="Est. - LOW", emp="~200-400", rev="Not public", rb="Private - NONE",
    nclients="Hundreds of agents/carriers", clients="Independent agents and carriers - buyer roster via partner disclosures",
    oe="Sells insurance leads and calls into buyer outbound programs",
    te="Structural: marketplace consent language binds every downstream buyer",
    lp="Originates + resells to many buyers",
    lit=6, lead=25, vol=13, vert=12, geo=8, gap=4,
    solv="Operating", fit="A - mid-market marketplace, compliance = differentiation",
    trig="Buyers increasingly require per-buyer named consent + TrustedForm audit trail",
    ep="General Counsel / VP Compliance / CEO",
    hook="Post-IMC your partner list is legal again - and it is also the exact document plaintiffs subpoena first.",
    src="industry marketplace listings", conf="LOW")

add(co="QuoteWizard (LendingTree)", v="Insurance", sv="Lead marketplace",
    bm="B2B lead seller", hq="Seattle, WA", sites="Seattle WA; Charlotte NC (parent)",
    seats="150-400 (est.)", sb="Est. - LOW", emp="Not separately disclosed", rev="LendingTree segment - not broken out", rb="Parent public - LOW",
    nclients="Carriers + agents", clients="P&C carriers and independent agents",
    oe="Sells insurance leads/calls to outbound buyers",
    te="Structural marketplace exposure; WA HQ under Washington's amended Commercial Electronic Mail/Solicitation Act with private right of action up to $1,000/violation",
    lp="Originates + resells",
    lit=7, lead=25, vol=13, vert=12, geo=8, gap=3,
    solv="Strong - NASDAQ parent", fit="B - parent legal team, but unit owns the risk",
    trig="Washington's strengthened mini-TCPA hits its home state operations directly",
    ep="Associate GC / VP Compliance",
    hook="Washington raised statutory damages to $1,000 per violation in your own back yard.",
    src="jdsupra WA/OK mini-TCPA analysis; LendingTree disclosures", conf="LOW-MEDIUM")

add(co="InsureMe, Inc.", v="Insurance", sv="Lead gen / agency",
    bm="B2C + B2B", hq="Not confirmed - verify", sites="Not confirmed",
    seats="Unknown", sb="Not researched - NONE", emp="Not public", rev="Not public", rb="Private - NONE",
    nclients="Unknown", clients="Not public",
    oe="Alleged 20+ unsolicited telemarketing calls to a single DNC-registered cell in 2024",
    te="Klouda v. InsureMe, Inc. - active TCPA suit alleging DNC-registry calls without express consent",
    lp="Alleged high-frequency outbound to purchased/unverified lists",
    lit=22, lead=22, vol=12, vert=12, geo=6, gap=5,
    solv="UNVERIFIED - diligence required before outreach", fit="B - real pain, unknown size/legitimacy",
    trig="Active litigation; small firms settle fast and then buy prevention",
    ep="Owner / General Counsel",
    hook="Twenty calls to one DNC number is not a dialer problem, it is a suppression-list problem. That is fixable this quarter.",
    src="Klouda v. InsureMe complaint reporting", conf="LOW - verify entity before contact")

add(co="GetMeHealthCare, LLC", v="Insurance", sv="Health insurance lead gen",
    bm="B2C + lead gen", hq="Florida (M.D. Fla. venue)", sites="FL",
    seats="Unknown", sb="Not researched - NONE", emp="Not public", rev="Not public", rb="Private - NONE",
    nclients="Unknown", clients="Not public",
    oe="Defendant in TCPA action arising from telemarketing calls",
    te="Smith v. GetMeHealthCare, LLC, No. 25-CV-00568 (M.D. Fla. 7/21/2026) - notably counter-sued the plaintiff for fraud and survived dismissal",
    lp="Unverified",
    lit=20, lead=20, vol=10, vert=12, geo=8, gap=5,
    solv="UNVERIFIED - diligence required", fit="B - actively fighting back, so budget exists",
    trig="Litigating aggressively (fraud counterclaim survived) - a buyer who invests in defense will invest in prevention",
    ep="Owner / General Counsel",
    hook="You are proving serial plaintiffs can be fought. Provenance evidence is what makes that fight cheap and repeatable.",
    src="Duane Morris Class Action Defense blog 7/29/2026", conf="LOW - verify entity")

# ---------------------------------------------------------- PERSONAL FINANCE
add(co="Beyond Finance", v="Personal Finance", sv="Debt consolidation / settlement",
    bm="B2C telesales", hq="Chicago, IL", sites="Houston, TX; Atlanta, GA; San Diego, CA",
    seats="1,500-2,500 (est.)", sb="Est. from multi-site telesales model - MEDIUM",
    emp="~2,000+ (incl. Accredited Debt Relief ~900)", rev="Not public", rb="Private - NONE",
    nclients="1.3M+ consumers served", clients="N/A - direct to consumer",
    oe="Multi-site consumer telesales operation across three metros",
    te="Structural: debt relief is ~22% of TCPA case mix (2nd highest vertical); heavy purchased-lead reliance",
    lp="Buys debt/financial-distress leads from aggregators",
    lit=10, lead=23, vol=19, vert=12, geo=8, gap=4,
    solv="Strong - scaled, 1.3M clients", fit="A - large outbound floor, no listed-company legal bench",
    trig="Debt relief is the #2 TCPA target vertical; CFPB/FTC also active on debt relief marketing",
    ep="Chief Compliance Officer / General Counsel",
    hook="Debt relief is the second most-sued vertical in TCPA. Your lead vendors decide your exposure, and you cannot currently prove what they captured.",
    src="beyondfinance.com fast facts; BBB profile; WebRecon vertical case mix", conf="MEDIUM")

add(co="National Debt Relief", v="Personal Finance", sv="Debt settlement",
    bm="B2C telesales", hq="New York, NY", sites="NY; remote",
    seats="800-1,500 (est.)", sb="Est. - LOW", emp="~1,000+", rev="Not public", rb="Private - NONE",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="High-volume consumer telesales for debt settlement enrollment",
    te="Structural: top-2 TCPA vertical; consumer-distress targeting attracts plaintiff bar",
    lp="Buys distress-signal leads from aggregators",
    lit=10, lead=23, vol=18, vert=12, geo=8, gap=4,
    solv="Strong - major national brand", fit="A",
    trig="Vertical base rate + regulator attention on debt relief marketing",
    ep="Chief Compliance Officer / General Counsel",
    hook="Financial-distress leads are the most re-sold data in the market. You are dialing consent you have never seen.",
    src="industry positioning; WebRecon vertical case mix", conf="LOW-MEDIUM")

add(co="Americor", v="Personal Finance", sv="Debt relief / consolidation",
    bm="B2C telesales", hq="Irvine, CA", sites="Irvine, CA",
    seats="400-900 (est.)", sb="Est. - LOW", emp="~700-1,000", rev="Not public", rb="Private - NONE",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="Consumer telesales for debt settlement/consolidation enrollment",
    te="Structural: top-2 TCPA vertical; CA base adds state consumer-protection overlay",
    lp="Buys distress leads",
    lit=9, lead=22, vol=16, vert=12, geo=7, gap=4,
    solv="Operating - founded 2009", fit="A - mid-market, reachable",
    trig="Vertical base rate; sector-wide regulator scrutiny",
    ep="General Counsel / VP Compliance",
    hook="Every lead you buy carries someone else's disclosure language. In discovery that language becomes yours.",
    src="company profile; WebRecon vertical case mix", conf="LOW")

add(co="AmeriSave Mortgage", v="Personal Finance", sv="Mortgage lending",
    bm="B2C telesales", hq="Atlanta, GA", sites="Atlanta GA; multiple US",
    seats="800-1,500 (est.)", sb="Est. - LOW", emp="~1,500+", rev="Not public", rb="Private - NONE",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="High-volume mortgage telesales on purchased trigger/refi leads",
    te="Named among recent mortgage-industry TCPA class action defendants",
    lp="Buys credit-trigger and refi leads - among the most aggressively resold lead types",
    lit=20, lead=24, vol=18, vert=12, geo=8, gap=4,
    solv="Operating - major nonbank lender", fit="A - active litigation + no listed-company legal bench",
    trig="Active TCPA class action wave hitting mortgage lenders; rate moves spike refi dialing",
    ep="Chief Compliance Officer / General Counsel",
    hook="Credit-trigger leads are resold within minutes. You are the deep pocket at the end of a chain you cannot document.",
    src="National Mortgage News TCPA class action coverage", conf="MEDIUM")

add(co="Rocket Mortgage", v="Personal Finance", sv="Mortgage lending",
    bm="B2C telesales", hq="Detroit, MI", sites="Detroit MI; Cleveland OH; Phoenix AZ",
    seats="3,000+ (est.)", sb="Est. from banker headcount - MEDIUM", emp="~14,000", rev="~$5B+", rb="Public filings - HIGH",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="One of the largest mortgage telesales operations in the US",
    te="Named among recent mortgage-industry TCPA class action defendants",
    lp="Mix of owned first-party and purchased leads",
    lit=19, lead=18, vol=20, vert=12, geo=8, gap=2,
    solv="Strong - NYSE listed", fit="C - large in-house legal/compliance function",
    trig="Mortgage TCPA filing wave; rate-cycle dialing surges",
    ep="Chief Compliance Officer / Associate GC",
    hook="At your dial volume, a 0.1% consent-provenance gap is a certifiable class.",
    src="National Mortgage News TCPA class action coverage; public filings", conf="MEDIUM-HIGH")

add(co="loanDepot", v="Personal Finance", sv="Mortgage lending",
    bm="B2C telesales", hq="Irvine, CA", sites="Irvine CA; Plano TX; multiple",
    seats="1,500-2,500 (est.)", sb="Est. - LOW", emp="~4,000-5,000", rev="~$1B+", rb="Public filings - HIGH",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="National mortgage telesales operation",
    te="Structural: mortgage is an active TCPA filing wave vertical; heavy purchased-lead reliance",
    lp="Buys refi/trigger leads",
    lit=12, lead=22, vol=18, vert=12, geo=8, gap=3,
    solv="Adequate - NYSE listed", fit="B",
    trig="Mortgage TCPA wave; rate-driven dialing surges",
    ep="Chief Compliance Officer / General Counsel",
    hook="Eleven new mortgage TCPA class actions landed in one recent filing wave. Trigger-lead provenance is the common thread.",
    src="National Mortgage News; public filings", conf="MEDIUM")

add(co="LoanStream Mortgage", v="Personal Finance", sv="Mortgage lending",
    bm="B2C/B2B lending", hq="Irvine, CA", sites="Irvine, CA",
    seats="200-500 (est.)", sb="Est. - LOW", emp="~500", rev="Not public", rb="Private - NONE",
    nclients="Brokers + consumers", clients="Wholesale broker network",
    oe="Outbound lending calls; defended a 50,000-member putative TCPA class",
    te="Won summary judgment 8/2026 after a TWO-YEAR TCPA class defense (50,000+ putative class)",
    lp="Purchased + broker-sourced leads",
    lit=16, lead=20, vol=13, vert=12, geo=7, gap=4,
    solv="Operating", fit="A - just paid two years of defense costs to win; maximum motivation to prevent round two",
    trig="Won on summary judgment 8/2026 - the relief is fresh and the defense invoice is fresher",
    ep="General Counsel / Chief Compliance Officer",
    hook="You won - after two years and a 50,000-member class scare. Provenance is what makes the next one end at the pleadings.",
    src="National Mortgage News 8/2026", conf="MEDIUM")

add(co="Achieve (Freedom Financial Network)", v="Personal Finance", sv="Debt resolution / lending",
    bm="B2C telesales", hq="San Mateo, CA", sites="Tempe AZ; San Mateo CA; Lake Mary FL",
    seats="1,000-2,000 (est.)", sb="Est. from multi-site model - LOW", emp="~2,500+", rev="Not public", rb="Private - NONE",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="Multi-site consumer telesales across debt resolution and lending products",
    te="Structural: debt relief vertical base rate; FL site adds FTSA exposure",
    lp="Buys financial-distress leads",
    lit=9, lead=22, vol=18, vert=12, geo=8, gap=4,
    solv="Strong", fit="A", trig="Vertical base rate + FL operations under FTSA",
    ep="Chief Compliance Officer / General Counsel",
    hook="Your Lake Mary floor is dialing under FTSA rules that the federal vacatur never touched.",
    src="company profile; FTSA analysis", conf="LOW-MEDIUM")

add(co="ClearOne Advantage", v="Personal Finance", sv="Debt settlement",
    bm="B2C telesales", hq="Baltimore, MD", sites="Baltimore, MD",
    seats="300-700 (est.)", sb="Est. - LOW", emp="~500-800", rev="Not public", rb="Private - NONE",
    nclients="Consumers (direct)", clients="N/A - direct to consumer",
    oe="Consumer debt settlement telesales",
    te="Maryland HQ - Maryland enacted a mini-TCPA in the FTSA mold, applying stricter standards to calls/texts to MD residents",
    lp="Buys distress leads",
    lit=8, lead=22, vol=15, vert=12, geo=8, gap=4,
    solv="Operating", fit="A - mid-market, state-law exposure in home state",
    trig="Maryland mini-TCPA applies to its home-state dialing",
    ep="General Counsel / VP Compliance",
    hook="Maryland adopted FTSA-style rules. Your home state is now your highest-risk calling jurisdiction.",
    src="state mini-TCPA tracker; company profile", conf="LOW")

# ------------------------------------------------------------------- SOLAR
add(co="Momentum Solar (Pro Custom Solar LLC)", v="Solar", sv="Residential solar EPC",
    bm="B2C direct sales", hq="South Plainfield, NJ", sites="NJ, NY, CA, FL, TX, CT, PA, AZ, NV, MA",
    seats="400-800 (est.)", sb="Est. from inside-sales share of ~2,000 staff - LOW",
    emp="~1,349-2,000+", rev="~$161.8M", rb="Aggregator estimate (Growjo) - LOW",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Telemarketing calls to consumers over a ~10-year class period (3/2015-1/2025)",
    te="Up to $30M TCPA class settlement (2025) - largest solar TCPA settlement to date; two consolidated D.N.J. class actions",
    lp="Purchased + self-generated solar leads",
    lit=30, lead=22, vol=15, vert=11, geo=8, gap=4,
    solv="Operating - but $30M settlement is a material balance-sheet event; verify", fit="A - settlement mandates remediation",
    trig="Settlement administration underway; a consent decree-style compliance obligation is the classic CiV entry",
    ep="General Counsel / Chief Compliance Officer / CEO",
    hook="A $30M settlement buys a fix once. The class period ran ten years because nothing was measuring it.",
    src="claimdepot; classaction.org; topclassactions; lawobrien", conf="HIGH on settlement")

add(co="Trinity Solar", v="Solar", sv="Residential solar EPC",
    bm="B2C direct sales", hq="Wall Township, NJ", sites="NJ, NY, CT, MA, RI, MD",
    seats="300-700 (est.)", sb="Est. from inside sales share of ~2,040 staff - LOW",
    emp="~2,040", rev="~$599.8M", rb="Aggregator estimate (Growjo) - LOW",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Large multi-state residential solar sales operation with inside sales/appointment setting",
    te="Structural: solar vertical has >$57M in disclosed TCPA settlements since 2018; peer Momentum settled for $30M",
    lp="Purchased + self-generated leads; appointment-setting vendors",
    lit=8, lead=22, vol=16, vert=11, geo=8, gap=4,
    solv="Strong - family-owned, ~$600M revenue, survived the shakeout", fit="A - solvent solar is now rare and this is the best of it",
    trig="Peer settlements ($30M Momentum) + competitor bankruptcies = board-level risk attention",
    ep="General Counsel / VP Sales Operations / CFO",
    hook="Your two closest competitors settled for $30M or filed Chapter 11. You are the solvent one left holding the vertical's risk profile.",
    src="growjo; zoominfo; solar TCPA settlement aggregates", conf="MEDIUM")

add(co="Sunrun Inc.", v="Solar", sv="Residential solar / storage",
    bm="B2C direct + dealer", hq="San Francisco, CA", sites="Multiple US",
    seats="800-1,500 (est.)", sb="Est. - LOW", emp="~10,000+", rev="~$2B+", rb="Public filings - HIGH",
    nclients="N/A + dealer network", clients="N/A direct; dealer/channel partners not fully public",
    oe="Direct and dealer-channel consumer sales including outbound calling",
    te="Named in comparative solar litigation analyses; dealer-channel calling creates vicarious exposure",
    lp="Dealer network sources leads independently - classic uncontrolled-channel risk",
    lit=12, lead=23, vol=17, vert=11, geo=8, gap=3,
    solv="Strong - NASDAQ listed, largest US residential solar", fit="B - large but dealer channel is genuinely ungoverned",
    trig="Dealer-model peers (Freedom Forever, Sunnova) collapsed partly under channel-conduct liabilities",
    ep="Chief Compliance Officer / VP Channel Operations",
    hook="Freedom Forever and Sunnova both ran dealer models and both filed Chapter 11 carrying channel-conduct claims. Your dealers dial in your name.",
    src="lawobrien solar litigation comparison; public filings; bankruptcy coverage", conf="MEDIUM")

add(co="Palmetto Solar", v="Solar", sv="Residential solar platform",
    bm="B2C + partner network", hq="Charleston, SC", sites="Remote-first + partner network",
    seats="200-500 (est.)", sb="Est. - LOW", emp="~1,000", rev="Not public", rb="Private - NONE",
    nclients="Installer/partner network", clients="Partner installer network (LightReach platform)",
    oe="Platform + partner sales model with outbound customer acquisition",
    te="Structural: solar vertical risk; partner-channel calling exposure",
    lp="Partner-sourced leads with variable consent capture",
    lit=6, lead=22, vol=13, vert=11, geo=8, gap=4,
    solv="Operating - one of the surviving platforms", fit="A - platform model means one fix protects many partners",
    trig="Post-shakeout consolidation; platform players inherit partners from failed competitors along with their lead files",
    ep="General Counsel / VP Partner Operations",
    hook="You are absorbing partners from collapsed dealer networks - and their lead files. Inherited leads are inherited liability.",
    src="industry coverage of solar consolidation", conf="LOW")

add(co="US Solar Connect", v="Solar", sv="Solar lead gen / sales",
    bm="B2C/B2B", hq="Not confirmed - verify", sites="FL nexus (FTSA claim)",
    seats="Unknown", sb="Not researched - NONE", emp="Not public", rev="Not public", rb="Private - NONE",
    nclients="Unknown", clients="Not public",
    oe="Alleged autodialed calls to DNC-registered numbers",
    te="Tom v. US Solar Connect - TCPA class action pleading BOTH a National DNC Registry class AND a Florida Telephone Solicitation Act autodial class",
    lp="Alleged autodialing of unverified lists",
    lit=23, lead=22, vol=12, vert=11, geo=8, gap=5,
    solv="UNVERIFIED - diligence required", fit="B - acute pain, unknown size",
    trig="Dual federal + FTSA class pleading - the doubled-damages structure that forces fast settlements",
    ep="Owner / General Counsel",
    hook="A stacked DNC + FTSA class means two statutory damages awards on one call. That math ends companies.",
    src="natlawreview solar lead company TCPA coverage", conf="LOW - verify entity")

add(co="EMPWR Solar", v="Solar", sv="Residential solar",
    bm="B2C direct sales", hq="Pennsylvania nexus (E.D. Pa. venue)", sites="PA/NJ region",
    seats="Unknown", sb="Not researched - NONE", emp="Not public", rev="Not public", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Defendant in TCPA action over solicitation calls",
    te="Shelton v. EMPWR Solar, 2026 WL 2244025 (E.D. Pa. Aug 4, 2026) - court found the serial-litigator plaintiff's number was NOT on the DNC list (favorable outcome)",
    lp="Unverified",
    lit=15, lead=20, vol=10, vert=11, geo=7, gap=5,
    solv="UNVERIFIED - diligence required", fit="B - just learned serial litigators target them",
    trig="Won on the DNC-status facts - a near miss that proves list hygiene decides outcomes",
    ep="Owner / VP Sales",
    hook="You won because the number was not actually on the DNC list. That was record-keeping luck. Make it a control.",
    src="Shelton v. EMPWR Solar, E.D. Pa. 8/4/2026", conf="LOW - verify entity")

# ------------------------------------------------- HVAC / HOME SERVICES
add(co="Power Home Remodeling Group", v="HVAC / Home Services", sv="Exterior remodeling",
    bm="B2C direct sales", hq="Chester, PA", sites="~20 US regional offices",
    seats="600-1,200 (est.)", sb="Est. from inside sales/canvassing share of ~3,000 - LOW",
    emp="~3,000", rev="~$1B (2022)", rb="Reported - MEDIUM",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Large inside-sales and appointment-setting operation supporting in-home selling",
    te="Active class action (2026) alleging violation of federal telemarketing law and state consumer protection statutes; settlement discussions reported underway",
    lp="Self-generated + purchased appointment-setting leads",
    lit=24, lead=20, vol=17, vert=10, geo=8, gap=4,
    solv="Strong - ~$1B revenue, No. 3 in 2026 Top 500 remodelers", fit="A - active case, solvent, no in-house TCPA bench",
    trig="Settlement discussions reported underway in 2026 - remediation design window is open right now",
    ep="General Counsel / Chief Compliance Officer",
    hook="Settlement talks are the moment to design the fix, while the number is still negotiable and remediation counts as good faith.",
    src="lawfold.com Power Home Remodeling class action 2026; Qualified Remodeler Top 500", conf="MEDIUM")

add(co="Leaf Home", v="HVAC / Home Services", sv="Gutter protection / home solutions",
    bm="B2C direct sales", hq="Hudson, OH", sites="200+ regional sales & field support offices; New York, NY",
    seats="1,000-2,000 (est.)", sb="Est. from inside sales share of ~4,132 - LOW",
    emp="~4,132 (Mar 2026)", rev="$2.53B (2025 remodeling revenue, +43.2% YoY)", rb="Qualified Remodeler Top 500 - HIGH",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="200+ office footprint with centralized appointment-setting and inside sales",
    te="Structural: highest-revenue US remodeler with mass-market outbound appointment setting; peer Power Home in active litigation",
    lp="Heavy purchased lead + appointment-setting vendor reliance",
    lit=9, lead=22, vol=19, vert=10, geo=8, gap=4,
    solv="Strong - No. 1 US remodeler at $2.53B, growing 43% YoY", fit="A - biggest solvent target in the vertical",
    trig="43% YoY growth = dialing scaled faster than controls; peer litigation rising",
    ep="General Counsel / Chief Compliance Officer / VP Sales Ops",
    hook="You grew remodeling revenue 43% in a year. Consent controls almost never scale at that rate - and the class period starts the day they stop.",
    src="Qualified Remodeler 2026 Top 500; Revelio Labs headcount; growjo", conf="MEDIUM-HIGH on size")

add(co="Long Home Products", v="HVAC / Home Services", sv="Roofing / baths / windows",
    bm="B2C direct sales", hq="Savage, MD", sites="Mid-Atlantic + expanding",
    seats="150-400 (est.)", sb="Est. - LOW", emp="~800-1,200", rev="Not public", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="CONFIRMED Convoso outbound dialer customer (named in Convoso customer materials)",
    te="Maryland HQ under Maryland's mini-TCPA; confirmed predictive-dialer operator in a high-complaint vertical",
    lp="Purchased + self-generated appointment leads",
    lit=8, lead=20, vol=18, vert=10, geo=8, gap=5,
    solv="Operating - established regional brand", fit="A - confirmed dialer + mid-market + no in-house bench",
    trig="Confirmed aggressive outbound dialer in a state that just adopted FTSA-style rules",
    ep="General Counsel / VP Marketing / COO",
    hook="You run a predictive dialer out of Maryland, which just adopted FTSA-style rules. That combination is what the plaintiff bar screens for.",
    src="convoso.com customer references; state mini-TCPA tracker", conf="MEDIUM on dialer")

add(co="Renewal by Andersen", v="HVAC / Home Services", sv="Window replacement",
    bm="B2C direct + franchise", hq="Cottage Grove, MN", sites="National franchise/affiliate network",
    seats="800-1,500 (est.)", sb="Est. across corporate + affiliate call centers - LOW",
    emp="~4,000+ (incl. affiliates)", rev="Not separately disclosed (Andersen Corp subsidiary)", rb="Private parent - LOW",
    nclients="N/A + franchise network", clients="N/A direct; franchise/affiliate network",
    oe="National appointment-setting call center operation supporting in-home sales",
    te="Structural: franchise/affiliate calling creates vicarious liability across an uncontrolled network",
    lp="Corporate + affiliate-purchased leads with inconsistent capture",
    lit=8, lead=22, vol=17, vert=10, geo=8, gap=4,
    solv="Strong - Andersen Corporation subsidiary", fit="B - franchise governance problem is a strong fit for provenance tooling",
    trig="Franchise-network calling is the exact structure Farmers just settled twice over",
    ep="General Counsel / VP Franchise Compliance",
    hook="Farmers settled twice for calls its appointed agents placed. Your affiliate network has the same structure and the same blind spot.",
    src="company footprint; Farmers vicarious liability analogy", conf="LOW-MEDIUM")

add(co="Modernize (QuinStreet)", v="HVAC / Home Services", sv="Home improvement lead gen",
    bm="B2B lead seller", hq="Austin, TX", sites="Austin TX; QuinStreet Foster City CA",
    seats="100-300 (est.)", sb="Est. - LOW", emp="Not separately disclosed", rev="QuinStreet segment - not broken out", rb="Parent public - LOW",
    nclients="Thousands of contractors", clients="HVAC, solar, roofing, window contractors nationwide",
    oe="Accused of cold calling using automatic dialing systems with prerecorded messages",
    te="TCPA class action settlement over cold calls placed with an ATDS and prerecorded messages",
    lp="Originates and resells home improvement leads to thousands of contractor buyers",
    lit=22, lead=25, vol=14, vert=10, geo=8, gap=3,
    solv="Strong - NASDAQ parent (QuinStreet)", fit="A - sells into exactly CiV's target verticals; a channel partner as much as a prospect",
    trig="Settled TCPA class action; its thousands of contractor buyers are ALSO CiV prospects",
    ep="General Counsel / VP Compliance",
    hook="Every contractor you sell to inherits your consent language. Certifiable provenance is a wedge against every competitor in your category.",
    src="topclassactions Modernize settlement; QuinStreet disclosures", conf="MEDIUM")

add(co="Farha Roofing, LLC", v="HVAC / Home Services", sv="Roofing",
    bm="B2C direct sales", hq="Wichita, KS", sites="KS/MO region",
    seats="20-60 (est.)", sb="Est. - LOW", emp="~100-250", rev="Not public", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Sent non-emergency advertising/marketing texts to consumer cell phones",
    te="$250,000 TCPA class settlement - texts without consent and without required sender identification",
    lp="Self-generated + purchased local leads",
    lit=20, lead=16, vol=8, vert=10, geo=6, gap=5,
    solv="Operating - small regional", fit="C - too small for enterprise pricing; useful as a proof-point case study",
    trig="Recent settlement; small firms rebuild process after paying",
    ep="Owner / Marketing Director",
    hook="A $250K settlement for missing sender ID in a text. The fix costs a fraction of that.",
    src="claimdepot Farha Roofing settlement", conf="MEDIUM on settlement")

add(co="Apex Service Partners", v="HVAC / Home Services", sv="PE-backed HVAC/plumbing platform",
    bm="B2C multi-brand rollup", hq="Tampa, FL", sites="National - 100+ acquired brands",
    seats="500-1,500 (est. across brands + central CX)", sb="Est. across rollup portfolio - LOW",
    emp="~10,000+", rev="Not public (PE-backed, Alpine Investors)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Multi-brand service platform with centralized and local outbound (maintenance renewal, membership, rebooking calls)",
    te="Structural: FL HQ (FTSA); each acquisition imports an un-audited customer list and its consent history",
    lp="Inherits customer/lead lists via acquisition - consent provenance rarely diligenced",
    lit=6, lead=23, vol=16, vert=10, geo=8, gap=5,
    solv="Strong - Alpine Investors backed, largest US HVAC platform", fit="A - roll-ups are the single best-fit structure for provenance tooling",
    trig="Every acquisition imports unverified consent; FL domicile adds FTSA; PE exit diligence will price the liability",
    ep="General Counsel / VP Integration / CFO",
    hook="Every tuck-in you close imports a customer list nobody diligenced for consent. You are buying calling rights you cannot prove.",
    src="ctacquisitions HVAC PE tracker 2026; Orbital largest HVAC companies", conf="MEDIUM on structure")

add(co="Wrench Group", v="HVAC / Home Services", sv="PE-backed HVAC/plumbing platform",
    bm="B2C multi-brand rollup", hq="Atlanta, GA", sites="National multi-brand",
    seats="400-1,000 (est.)", sb="Est. - LOW", emp="~5,000+", rev="Not public (Leonard Green & Partners)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Multi-brand HVAC/plumbing platform with membership renewal and rebooking call operations",
    te="Structural: acquisition-driven list inheritance; multi-state calling footprint",
    lp="Inherits lists via acquisition",
    lit=5, lead=23, vol=15, vert=10, geo=8, gap=5,
    solv="Strong - Leonard Green backed", fit="A - roll-up structure",
    trig="Continued tuck-in acquisitions; PE hold-period exit prep",
    ep="General Counsel / VP Operations / CFO",
    hook="Roll-ups inherit calling lists faster than they inherit calling controls.",
    src="ctacquisitions HVAC PE tracker 2026", conf="MEDIUM on structure")

add(co="ARS/Rescue Rooter", v="HVAC / Home Services", sv="PE-backed HVAC/plumbing platform",
    bm="B2C multi-brand", hq="Memphis, TN", sites="70+ US locations",
    seats="500-1,200 (est.)", sb="Est. - LOW", emp="~7,000+", rev="Not public (GI Partners / American Securities)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="National HVAC/plumbing service network with centralized call center and membership renewal calling",
    te="Structural: national multi-state calling; membership renewal campaigns to legacy customer lists",
    lp="Legacy customer lists + purchased leads",
    lit=5, lead=21, vol=16, vert=10, geo=8, gap=5,
    solv="Strong - PE backed, national scale", fit="A",
    trig="Membership renewal campaigns dial legacy lists whose consent predates current rules",
    ep="General Counsel / VP Customer Operations",
    hook="Membership renewal calls to a legacy list are the most common unexamined TCPA exposure in home services.",
    src="ctacquisitions HVAC PE tracker 2026; Orbital", conf="MEDIUM on structure")

add(co="Service Experts Heating & Air", v="HVAC / Home Services", sv="PE-backed HVAC platform",
    bm="B2C multi-brand", hq="Plano, TX", sites="~90 US/Canada centers",
    seats="400-900 (est.)", sb="Est. - LOW", emp="~4,000+", rev="Not public (Brookfield / Morgan Stanley Capital Partners)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Multi-location HVAC service network with maintenance agreement renewal calling",
    te="Structural: TX HQ (TX telemarketing registration + bond required); multi-state renewal calling",
    lp="Legacy lists + purchased leads",
    lit=5, lead=21, vol=15, vert=10, geo=8, gap=5,
    solv="Strong - institutional ownership", fit="A",
    trig="Texas requires telemarketer registration and bond; multi-state renewal campaigns",
    ep="General Counsel / VP Operations",
    hook="Ninety locations dialing renewals under thirty different state registration regimes.",
    src="ctacquisitions HVAC PE tracker 2026", conf="MEDIUM on structure")

add(co="Sila Services", v="HVAC / Home Services", sv="PE-backed HVAC platform",
    bm="B2C multi-brand rollup", hq="Newtown Square, PA", sites="Northeast/Mid-Atlantic multi-brand",
    seats="200-600 (est.)", sb="Est. - LOW", emp="~3,000+", rev="Not public (Goldman Sachs Alternatives)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Regional multi-brand HVAC platform with service renewal calling",
    te="Structural: acquisition-driven list inheritance; MD/PA footprint includes a mini-TCPA state",
    lp="Inherits lists via acquisition",
    lit=5, lead=22, vol=14, vert=10, geo=8, gap=5,
    solv="Strong - Goldman Sachs Alternatives backed", fit="A",
    trig="Active tuck-in acquirer; Maryland mini-TCPA in its service footprint",
    ep="General Counsel / VP Integration",
    hook="Goldman will diligence this at exit. Better to build the record now than reconstruct it under a data request.",
    src="ctacquisitions HVAC PE tracker 2026", conf="MEDIUM on structure")

add(co="TurnPoint Services", v="HVAC / Home Services", sv="PE-backed HVAC platform",
    bm="B2C multi-brand rollup", hq="Louisville, KY", sites="National multi-brand",
    seats="200-600 (est.)", sb="Est. - LOW", emp="~3,000+", rev="Not public (OMERS)", rb="Private - NONE",
    nclients="N/A", clients="N/A - direct to consumer",
    oe="Multi-brand home services platform with centralized customer contact operations",
    te="Structural: acquisition-driven list inheritance across multiple states",
    lp="Inherits lists via acquisition",
    lit=5, lead=22, vol=14, vert=10, geo=8, gap=5,
    solv="Strong - OMERS (pension fund) backed", fit="A - institutional owner means institutional risk appetite",
    trig="Pension-fund ownership means low tolerance for contingent consumer-protection liability",
    ep="General Counsel / CFO",
    hook="A pension fund owns you. Contingent statutory-damages exposure is exactly what their risk committee screens.",
    src="ctacquisitions HVAC PE tracker 2026", conf="MEDIUM on structure")

# ------------------------------------------- BPO / OUTSOURCED CALL CENTERS
add(co="Mass Markets (MCI)", v="BPO / Outsourced", sv="Outbound telesales BPO",
    bm="B2B outsourced calling", hq="Iowa City, IA (parent MCI, Miami Beach, FL)",
    sites="8 US contact centers incl. 500+ seat Sioux City, IA facility",
    seats="~2,500 (across 8 centers); Sioux City alone 500+", sb="Company/press disclosed - HIGH",
    emp="~2,500", rev="Not public", rb="Private - NONE",
    nclients="Multiple enterprise clients", clients="Client roster not public - B2B and B2C telesales clients across verticals",
    oe="EXPLICITLY markets outbound telesales B2B and B2C contact center services",
    te="Structural: performs outbound calling AS AGENT for clients - the purest vicarious liability posture in the list",
    lp="Dials client-supplied lists whose consent it did not capture",
    lit=6, lead=25, vol=20, vert=9, geo=8, gap=4,
    solv="Strong - growing, adding US capacity", fit="A - BPOs must prove compliance to WIN deals; CiV is a revenue tool not a cost",
    trig="Actively expanding US seat capacity; enterprise clients now demand TCPA indemnity and audit rights in MSAs",
    ep="General Counsel / VP Compliance / Chief Revenue Officer",
    hook="You dial lists you did not build under indemnities you cannot verify. Provable provenance wins the deals your competitors cannot underwrite.",
    src="massmarkets.com; mci.world; Sioux City Journal facility coverage", conf="HIGH on seats")

add(co="Alorica", v="BPO / Outsourced", sv="CX BPO with outbound programs",
    bm="B2B outsourced", hq="Irvine, CA", sites="100+ locations across 14-16 countries incl. large US footprint",
    seats="10,000+ US (est. of 100k+ global)", sb="Est. from global footprint - LOW",
    emp="~100,000 globally", rev="Not public", rb="Private - NONE",
    nclients="Large enterprise roster; avg client tenure ~10 yrs", clients="Client roster not public - telecom, retail, financial services, healthcare",
    oe="Processes 3B+ interactions annually including outbound programs",
    te="Structural: agent-of-client calling posture across regulated verticals",
    lp="Dials client-supplied lists",
    lit=5, lead=23, vol=19, vert=9, geo=8, gap=3,
    solv="Strong - one of largest US-headquartered BPOs", fit="B - large, likely has compliance function; sell as differentiation",
    trig="Financial services and healthcare clients pushing TCPA indemnity downstream",
    ep="Chief Compliance Officer / General Counsel",
    hook="Your clients are moving TCPA indemnity into the MSA. Provenance evidence is how you price that risk instead of absorbing it.",
    src="alorica.com; helpware/outsourceaccelerator BPO rankings", conf="MEDIUM")

add(co="TTEC Holdings", v="BPO / Outsourced", sv="CX BPO with outbound/sales programs",
    bm="B2B outsourced", hq="Englewood, CO", sites="Multiple US + global",
    seats="~15,000 US (est. of 61,000 global)", sb="Est. - LOW", emp="~61,000", rev="~$2.1B", rb="Public filings - HIGH",
    nclients="Enterprise roster", clients="Client roster not public - healthcare, financial services, telecom, automotive",
    oe="Operates outbound sales and acquisition programs for enterprise clients",
    te="Structural: agent-of-client calling in healthcare and financial services",
    lp="Dials client-supplied lists",
    lit=5, lead=23, vol=18, vert=9, geo=8, gap=3,
    solv="Strong - NASDAQ listed", fit="B",
    trig="Healthcare/financial services clients demanding auditable consent handling",
    ep="Chief Compliance Officer / General Counsel",
    hook="Regulated-vertical clients now audit how you handle consent. Being auditable is a competitive moat in BPO bids.",
    src="BPO industry rankings; public filings", conf="MEDIUM-HIGH on financials")

add(co="IBEX Limited", v="BPO / Outsourced", sv="CX BPO with outbound programs",
    bm="B2B outsourced", hq="Washington, DC", sites="US + nearshore/offshore",
    seats="3,000-6,000 US (est.)", sb="Est. - LOW", emp="~30,000", rev="~$500M+", rb="Public filings - MEDIUM",
    nclients="Enterprise roster", clients="Client roster not public - telecom, retail, fintech, healthcare",
    oe="Outbound sales and retention programs for clients",
    te="Structural: agent-of-client calling posture",
    lp="Dials client-supplied lists",
    lit=4, lead=22, vol=16, vert=9, geo=8, gap=4,
    solv="Strong - NASDAQ listed", fit="B",
    trig="Client MSAs adding TCPA audit rights",
    ep="General Counsel / VP Compliance",
    hook="Every outbound program you run for a client is a claim they will tender to you first.",
    src="BPO industry rankings; public filings", conf="MEDIUM")

# rank by score desc, then name
R.sort(key=lambda r: (-r["score"], r["co"]))

with open("/home/user/architecture-planning-marketplace/prospecting/civ-tcpa-prospect-list.csv","w",newline="",encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(H)
    for i, r in enumerate(R, 1):
        w.writerow([
            i, r["co"], r["v"], r["sv"], r["bm"], r["hq"], r["sites"],
            r["seats"], r["sb"], r["emp"], r["rev"], r["rb"],
            r["nclients"], r["clients"], r["oe"], r["te"], r["lp"],
            r["lit"], r["lead"], r["vol"], r["vert"], r["geo"], r["gap"],
            r["score"], band(r["score"]), r["solv"], r["fit"],
            r["trig"], r["ep"], r["hook"], r["src"], r["conf"],
        ])

print(f"rows: {len(R)}")
from collections import Counter
print("by band:", Counter(band(r['score']) for r in R).most_common())
print("by vertical:", Counter(r['v'] for r in R).most_common())
print("top 10:")
for i,r in enumerate(R[:10],1): print(f"  {i:2d}. {r['score']:3d}  {r['co']}")
